[msg]
    200         = "请求正常"
    400         = "非法操作！"
    401         = "认证失败！"
    404         = "页面丢失！"
    500         = "服务器内部错误！"
    1001        = "请登录后操作！"
    1002        = "登录信息已经过期，请重新登录！"
    1003        = "参数异常"

    2001        = "数据写入失败！(2001）"
    2002        = "数据更新失败！(2002）"
    2003        = "数据删除失败！(2003）"
    2004        = "数据查询失败！(2004）"

    3001        = "Token解析错误，请联系管理员"
    3002        = "解析参数异常"
    3003        = "参数转换为Map类型出错，请联系管理员"

